### ISSUE TITLE
A fresh install of Fledge using the archives repo for Ubuntu server 18.04 on RPi 4 4GB shows errors in system log

### ISSUE THREAD

**Issue by sudhirkshirsagar** [fledge-iot/fledge#152]
Aug 15 02:34:01 ubuntu Fledge Storage[17992]: ERROR: Failed to register configuration category: {"error": {"message": "[AttributeError] 'NoneType' object has no attribute 'register'"}}.

Aug 15 02:33:59 ubuntu Fledge Storage[17992]: ERROR: Failed to register configuration category: {"error": {"message": "[AttributeError] 'NoneType' object has no attribute 'register'"}}.

Aug 15 02:33:59 ubuntu Fledge Storage[17992]: ERROR: HTTP error while adding child categories: 404: No such Advanced category exist

**Comment by MarkRiddoch** [comment]
Thanks for bringing this to our attention, we have raised a Jira ticket for this [https://scaledb.atlassian.net/browse/FOGL-4451](https://scaledb.atlassian.net/browse/FOGL-4451) and plan to have this fixed in the next 2 week sprint cycle.

**Comment by muslui** [comment]
this is still an issue in 2.1.0 with ubuntu 18.04. Any idea to solve it?
![image](https://github.com/fledge-iot/fledge/assets/125678157/fd0d5e60-4d6c-4b8d-ba01-0b73b4aae8f1)
Purge operation fails when this error is presented on startup.

**Comment by TheVexy** [comment]
Still an issue in 2.4
